apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  namespace: default
spec:  
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: 594081136085.dkr.ecr.eu-north-1.amazonaws.com/golang:a5c3beed16880128859c7f9b84cc95619d85b034
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: /usr/local/bin/file.p12
      volumes:
      - name: secret-volume
        secret:
          secretName: go-app-secret
