apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-go-app
  namespace: default
spec:
  maxReplicas: 6
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1    
    kind: Rollout
    name: go-app
  targetCPUUtilizationPercentage: 50
